### ISSUE TITLE
Fails to compile with latest Rebar3

### ISSUE THREAD

**Issue by cjimison** [Kyorai/riak_core#21] opened 2017-06-16 19:44 UTC
Hello,

When I compile this project with the latest version of rebar3 I get the following errors:

===> Compiling blume
===> Compiling goldrush
===> Compiling lager
===> Compiling cuttlefish
===> Building escript...
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
==> sample
** (Mix) Could not compile dependency :cuttlefish, "/home/cjimison/.mix/rebar3 bare compile --paths "/home/cjimison/sample/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile cuttlefish", update it with "mix deps.update cuttlefish" or clean it with "mix deps.clean cuttlefish"

However when I revert my rebar3 to version 3.2.0 and rebar 2.6.2 it compiles fine.

Thanks,

-Chris

**Comment by Licenser** [comment] 2017-06-16 21:16
Can you share a few more details? The content of the .crashdump file, erlang versions, mix versions etc?

**Comment by Licenser** [comment] 2017-06-16 21:17
it compiles fine with:
`rebar 3.4.1 on Erlang/OTP 19 Erts 8.3`

**Comment by Licenser** [comment] 2017-07-21 12:18
Seems to be a duplicate of #23 which holds more information so I'm closing this. Plese if the problem consists engage in the above-mentioned issue instead.

**Closed as completed by Licenser** 2017-07-21 12:18 UTC
