### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Lazarus404** [Kyorai/riak_core#20] opened 2017-02-26 20:12 UTC
When compiling, I get an error that Cuttlefish can't be compiled.  The rebar3.crashdump for Cuttlefish reads

```erlang
Error: {badmatch,error}
[{rebar_prv_escriptize,find_deps_of_deps,3,
                       [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_escriptize.erl"},
                        {line,240}]},
 {rebar_prv_escriptize,find_deps,2,
                       [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_escriptize.erl"},
                        {line,234}]},
 {rebar_prv_escriptize,escriptize,2,
                       [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_escriptize.erl"},
                        {line,104}]},
 {rebar_prv_escriptize,do,1,
                       [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_escriptize.erl"},
                        {line,80}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,125}]},
 {rebar_hooks,run_provider_hooks_,6,
              [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_hooks.erl"},
               {line,49}]},
 {rebar_hooks,run_all_hooks,6,
              [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_hooks.erl"},
               {line,16}]},
 {rebar_prv_compile,compile,3,
                    [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_compile.erl"},
                     {line,129}]}]
```

I've tried this with Elixir 1.4.1 running in Erlang 19 and with Elixir 1.3.4 under Erlang 18.3.

**Comment by Licenser** [comment] 2017-02-27 01:20
Heya,
can you try compiling it with rebar3 directly to check weather it's a issue with the codebase or something about how mix handles things?

**Comment by Lazarus404** [comment] 2017-02-27 08:41
If I compile cuttlefish into an Erlang app using the same rebar in 
~/.mix/, it compiles fine.  I'm guessing it is to do with Mix, somehow.

**Comment by Licenser** [comment] 2017-02-27 11:37
yea that was my fear, I really know nothing about how mix works. I think the best bet is to ask the mix people, if it compiles w/ rebar then it's probably a bug that it doesn't compile with mix.

**Comment by Lazarus404** [comment] 2017-02-27 11:38
Okay, thanks.  I've a thread going on the Riak Core mailing list.  
Hopefully, I'll get to the bottom of it.  If I do, I'll update this thread.

**Comment by Licenser** [comment] 2017-02-27 11:40
awesome! if there is any change needed to `_ng` I'll make sure it gets in and publish it :)

**Comment by cibingeorge** [comment] 2017-03-22 14:47
@Lazarus404 i got this compiled with the code in github:
```
     {:cuttlefish, github: "basho/cuttlefish", tag: "2.0.11", manager: :rebar3, override: true},
     {:lager, ~r/.*/, github: "basho/lager", tag: "3.2.4", manager: :rebar3, override: true}
```
I am a elixir newbie, so not sure if this is exactly right

**Comment by Licenser** [comment] 2017-07-21 12:18
Seems to be a duplicate of #23 which holds more information so I'm closing this. Plese if the problem consists engage in the above-mentioned issue instead.

**Closed as completed by Licenser** 2017-07-21 12:18 UTC
